apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-replica-set
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-container
        image: pythonincontainers/simple-flask:v1.1
        ports:
        - containerPort: 5000
